# -*- mode: ruby -*-
#
# Vagrantfile - One development machine to rule them all.

Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/8"
  config.env.enable

  # Variables Environment
  username = ENV['USER']
  home = ENV['HOME']
  pubkey = ENV['PUBKEY']
  interface = ENV['IFACE']
  base_ip = ENV['BASEIP']
  netmask = ENV['NETMASK']
  gateway = ENV['GATEWAY']
  prefix = ENV['PREFIX']
  memory = ENV['MEMORY']
  cpu = ENV['CPU']
  group = ENV['GROUP']

  # Variables for VM Settings
  memory = "#{memory}"
  cpu = "#{cpu}"

  # Number of VMs Lab to create
  num_vms = 1

  # Loop through the count index
  (1..num_vms).each do |i|
    ip_parts = base_ip.split('.')
    ip_parts[3] = (ip_parts[3].to_i + i).to_s
    ip = ip_parts.join('.')
    
    config.vm.define "#{prefix}#{i}" do |vm|
      vm.vm.hostname = "#{prefix}#{i}"
      vm.vm.network "public_network", bridge: "#{interface}", ip: "#{ip}", netmask: "#{netmask}"
    
      vm.vm.provider "virtualbox" do |vm|
        # VM System Resources
        vm.customize ["modifyvm", :id, "--vram", "16", "--groups", "/#{group}", "--audio", "none"]
        vm.memory = "#{memory}"
        vm.cpus = "#{cpu}"
      end

      # Uncomment the following line if you want to use synced_folder between Host x VMs (Edit  mountpoints)
      vm.vm.synced_folder "#{home}/Public", "/sharing"

      vm.vm.provision "shell", inline: <<-SHELL
        # Adding Public DNS Resolvers
        echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf
        echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
        echo "nameserver 8.8.4.4" | sudo tee -a /etc/resolv.conf
        # Configure Default Network Gateway
        ip route add default via "#{gateway}"
        # Create Sysadmin/DevOps 'sudo' User plus accessing mechanism/permissions
        useradd -m -s /bin/bash -G vagrant "#{username}"
        echo "#{username}     ALL=(ALL)     NOPASSWD: ALL" | sudo tee -a /etc/sudoers.d/vagrant
        mkdir -p "/home/#{username}/.ssh"
        chmod 700 "/home/#{username}/.ssh"
        echo "#{pubkey}" | tee "/home/#{username}/.ssh/authorized_keys"
        chmod 600 "/home/#{username}/.ssh/authorized_keys"
        chown -R "#{username}:#{username}" "/home/#{username}/.ssh"
      SHELL

      # In case you want to install additional repositories, installations, etc... Uncomment the line below
      # Vagrant VM Provisioning

      vm.vm.provision "shell", path: "scripts/repo.sh"
      vm.vm.provision "shell", path: "scripts/provisioner.sh"
      #vm.vm.provision "shell", path: "scripts/salt.sh"
      #vm.vm.provision "shell", path: "scripts/ansible.sh"      
    end
  end
end
