# -*- mode: ruby -*-

Vagrant.configure("2") do |config|

  # Vagrant Addition Guest Plugin Configurations  --------------------
  # https://github.com/dotless-de/vagrant-vbguest --------------------
  # set auto_update to false, if you do NOT want to check the correct 
  # Additions version when booting this machine
  config.vbguest.auto_update = false  
  # Do NOT download the iso file from a webserver
  config.vbguest.no_remote = true

  # Enable Environment Plugin
  config.env.enable
  
  # Vagrant Box Distribution
  distro = ENV['DIST']
  version = ENV['VER']

  config.vm.box = "#{distro}/#{version}"

  # Variables for VM Settings
  memory = "#{memory}"
  cpu = "#{cpu}"

  # Variables Environment
  interface = ENV['IFACE']
  base_ip = ENV['BASEIP']
  netmask = ENV['NETMASK']
  gateway = ENV['GATEWAY']
  prefix = ENV['PREFIX']
  memory = ENV['MEMORY']
  cpu = ENV['CPU']
  group = ENV['GROUP']

  # User Variables
  username = ENV['USER']
  home = ENV['HOME']
  pubkey = ENV['PUBKEY']

  # Number of VMs Lab to create
  num_vms = 1

  # Loop through the count index
  (1..num_vms).each do |i|
    ip_parts = base_ip.split('.')
    ip_parts[3] = (ip_parts[3].to_i + i).to_s
    ip = ip_parts.join('.')
    
    config.vm.define "#{prefix}#{i}" do |vm|
      vm.vm.hostname = "#{prefix}#{i}"
      vm.vm.network "public_network", bridge: "#{interface}", ip: "#{ip}", netmask: "#{netmask}"
    
      vm.vm.provider "virtualbox" do |vm|
        # VM System Resources
        vm.customize ["modifyvm", :id, "--vram", "16", "--groups", "/#{group}", "--audio", "none", "--graphicscontroller", "vmsvga"]
        vm.memory = "#{memory}"
        vm.cpus = "#{cpu}"
      end

      vm.vm.provision "shell", inline: <<-SHELL
        # Create Linux "Sudo" User
        useradd -m -s /bin/bash -G vagrant "#{username}"
        echo "#{username}     ALL=(ALL)     NOPASSWD: ALL" | sudo tee -a /etc/sudoers.d/vagrant
        mkdir -p "/home/#{username}/.ssh"
        chmod 700 "/home/#{username}/.ssh"
        echo "#{pubkey}" | tee "/home/#{username}/.ssh/authorized_keys"
        chmod 600 "/home/#{username}/.ssh/authorized_keys"
        chown -R "#{username}:#{username}" "/home/#{username}/.ssh"
      SHELL

      vm.vm.provision "shell", inline: <<-SHELL
        # Adding Public DNS Resolvers
        echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
        echo "nameserver 208.67.222.222" | sudo tee -a /etc/resolv.conf
        echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
        # Configure Default Network Gateway
        ip route add default via "#{gateway}"
      SHELL

      # In case you want to install additional repositories, installations, etc... Uncomment the line below
      # Vagrant VM Provisioning

      #vm.vm.provision "shell", path: "scripts/repo.sh"
      #vm.vm.provision "shell", path: "scripts/provisioner.sh"

      # Virtualbox Sync Folders
      vm.vm.synced_folder '.', '/vagrant', disabled: true
      
      # Uncomment the following line if you want to use synced_folder between Host x VMs (Edit  mountpoints)
      #vm.vm.synced_folder "#{home}/Public", "/sharing", "automount": true, "SharedFoldersEnableSymlinksCreate": true
    end
  end
end
